# Generated by Django 3.2.6 on 2021-09-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('urltoimage', models.TextField(blank=True, db_column='urlToImage', null=True)),
                ('publishedat', models.DateTimeField(blank=True, db_column='publishedAt', null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('cleaned', models.TextField(blank=True, null=True)),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NEWS',
            },
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('num_comments', models.TextField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('upvote_ratio', models.FloatField(blank=True, null=True)),
                ('ups', models.BigIntegerField(blank=True, null=True)),
                ('downs', models.BigIntegerField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'REDDIT',
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('tweet', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('nlikes', models.BigIntegerField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TWITTER',
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('video_id', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('views', models.TextField(blank=True, null=True)),
                ('liked', models.TextField(blank=True, null=True)),
                ('disliked', models.TextField(blank=True, null=True)),
                ('comment_count', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'YOUTUBE',
            },
        ),
    ]
